# Book settings
title: | 
    DSE 2023 Lausanne
author: John Stachurski
only_build_toc_files: true

execute:
  execute_notebooks: 'off'

sphinx:
    extra_extensions: []
    config:
        html_js_files:
        - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
        html_theme: quantecon_book_theme
        html_theme_options:
            header_organisation_url: https://quantecon.org
            header_organisation: QuantEcon
            repository_url: https://github.com/quantecon/dse_2023
            twitter: quantecon
            twitter_logo_url: https://assets.quantecon.org/img/qe-twitter-logo.png
            og_logo_url: https://assets.quantecon.org/img/qe-og-logo.png
            description: |
                This website is the companion site for DSE 2023
        mathjax3_config:
            tex:
                macros:
                    "Exp" : ["\\operatorname{Exp}"]
                    "Binomial" : ["\\operatorname{Binomial}"]
                    "Poisson" : ["\\operatorname{Poisson}"]
                    "BB" : ["\\mathbb{B}"]
                    "EE" : ["\\mathbb{E}"]
                    "PP" : ["\\mathbb{P}"]
                    "RR" : ["\\mathbb{R}"]
                    "NN" : ["\\mathbb{N}"]
                    "ZZ" : ["\\mathbb{Z}"]
                    "dD" : ["\\mathcal{D}"]
                    "fF" : ["\\mathcal{F}"]
                    "lL" : ["\\mathcal{L}"]
                    "linop" : ["\\mathcal{L}(\\mathbb{B})"]
                    "linopell" : ["\\mathcal{L}(\\ell_1)"]

latex:
    latex_engine: "xelatex"
    latex_documents:
        targetname: book.tex
